### PR TITLE
Feature/jekyllify

### PR DESCRIPTION
**Pull request by mauricesvay**
Hello ParisJS!

This PR changes the way the site is updated to use Github flavored Jekyll. 
I've migrated all the existing content, added missing content and cleaned up some avatars that were 404.
For visitors, nothing should be really different, except that there is better content now :)

## How it works

* Content is now stored in `_posts` and `_data` instead of index.html.
* Each meetup is represented by a tag.
* Each talk is a jekyll post, stored in `_posts`, as markdown files.
* Each file contains a YAML head ("front matter" in Jekyll jargon) that contains all the data previously available in json. Fields are:
  * tags: contain the tag associated to the meetup. E.g: `parisjs41` for the last meetup.
  * title: title of the talk, in double quote strings
  * authors: list of authors
     * name: in double quote string
     * url: URL. Usually link to twitter profile.
     * avatar: URL. Usually link of twitter avatar.
  * projects: list of URLs
  * slides: list of URLs
  * videos: list of URLs
* At the moment, the markdown content only contains the talk title. When needed, we can generate a richer content from metadata. It could be interesting to add a description, author info and embed media with oEmbed in the future.
* Data on meetups (reprensented by Jekyll tags) is stored in `_data/meetups.yml`
  * The file contains the list of all tags used by meetups. Each meetup has those fields:
    * tag: associated tag
    * title: Titles format was inconsistent through time. I chose to store them as is instead of trying to generate them from data. We might want to fix that in the future
    * date: date of the meetup. Currently unused.

All this data is now displayed by `index.html`, which is now a template that iterates over all tags, fetches post and meetup data and display them.

Bonus point: Jekyll generates 1 page per talk. They are currently not linked (so virtually not there) because their content is very limited. We might want to change that if we make the content richer in the future. 
If you inspect the list of all talks, you should be able to discover the links to these pages.

## How to update the site

I've updated the README to explain how to update the site.
Please refer to it.

## Deploying the site

Simply merge `master` into `gh-pages` and push. Github takes care of the build process.

Feel free to discuss this PR. I'd be happy to answer any questions!

### CODE REVIEW

**Comment by jeromeetienne** [comment]
+1 to press the button merge and to keep it as simple and standard as possible.

ps: just my 2cents, je suis tombe dessus par hasard due a une recherche dans mes emails

**Comment by PierrickP** [comment]
goooooooooo
pas testé je fais confiance :smile:

**Comment by francois2metz** [comment]
En ligne temporairement à cette adresse: http://parisjs.github.io/parisjs-website

@peutetre tu peux changer les DNS ? https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/ 
C'est une record A qu'il faut ;)

**Comment by peutetre** [comment]
c'est fait !

**Comment by francois2metz** [comment]
:+1: Pour reconnaitre quelle version vous voyez, c'est simple: La nouvelle version a des avatars pour le dernier meetup.

**Comment by francois2metz** [comment]
- [ ] Remove master branch
- [ ] set gh-pages as the default one

**Comment by francois2metz** [comment]
@peutetre Tu pourrait rajouter 192.30.252.154 comment IP ?

Sinon c'est propagé chez moi ce matin \o/

**Comment by francois2metz** [comment]
@challet J'ai désactivé le webhoob vers push.parisjs.org. Tu peux donc enlever les vhosts.

**Comment by francois2metz** [comment]
Good job @mauricesvay :clap:

**Comment by peutetre** [comment]
done @francois2metz!

thanks @mauricesvay!

**Comment by molokoloco** [comment]
Merci a vous ! Chapo
https://twitter.com/parisjs/status/557119231599599616

:)

JG

On 19 January 2015 at 10:15, Paul Panserrieu <notifications@github.com>
wrote:

> done @francois2metz <https://github.com/francois2metz>!
>
> thanks @mauricesvay <https://github.com/mauricesvay>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parisjs/parisjs-website/pull/78#issuecomment-70464230>
> .
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr

**Comment by molokoloco** [comment]
Vous savez, avec prose.io, si on peut éditer les page wiki d'un projet
github ? Ca marchait après la migration de ma repo google code (les wikis
ont été transférés dans la branche "wiki" du projet - mais pas dans les
"pages wiki")
Je viens de migrer dans les "pages wiki" (non sans douleur) mais je peux
plus utiliser prose... moi triste ^^

2015-01-19 11:18 GMT+01:00 Julien G <molokoloco@gmail.com>:

>
> Merci a vous ! Chapo
> https://twitter.com/parisjs/status/557119231599599616
>
> :)
>
> JG
>
> On 19 January 2015 at 10:15, Paul Panserrieu <notifications@github.com>
> wrote:
>
>> done @francois2metz <https://github.com/francois2metz>!
>>
>> thanks @mauricesvay <https://github.com/mauricesvay>!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/parisjs/parisjs-website/pull/78#issuecomment-70464230>
>> .
>>
>
>
>
> --
> *Julien Guézennec *+336 61 75 64 98
> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
> http://b2bweb.fr
>



-- 
*Julien Guézennec *+336 61 75 64 98
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco <https://twitter.com/molokoloco/> -
http://b2bweb.fr

**Comment by DjebbZ** [comment]
Si j'ai bien compris prose.io ne permet d'éditer que des répo github "classiques", càd ceux qu'on voit dans l'interface. Techniquement, les wiki aussi sont des répo, puisqu'ils sont accessibles avec un git clone. Mais pas visibles dans la liste... Peut être qu'en le clonant et en le repoussant comme un dépôt classique ça peut marcher...

**Pull request closed without merging**
