### PR TITLE
Add i18n'ed titles to talk submission and sponsors pages

### PR DESCRIPTION
**Pull request by Haroenv**
I wasn't sure which to use for the description so left it as is, but maybe the `TALK_EXPLAIN` could work, can make another PR to try it out

### CODE REVIEW

**Comment by PierrickP** [comment]
not working on netlify.
I already tried something without sucess.
Thanks to take a look ;)

**Comment by Haroenv** [comment]
:( Not sure how to fix this, seems like the other titles just are hardcoded...

**Comment by mauricesvay** [comment]
I started looking into this issue a while ago, but I ending up in a rabbit hole. `FormattedMessage` wraps everything into a `<span>`, which doesn't work for `<title>`. And, weirdly, react-intl doesn't provide a method for simply translating a string.

**Comment by Haroenv** [comment]
Maybe using the underlying FormatJS could help?

**Pull request closed without merging**
